config/routes.rb
Cms::Application.routes.draw do
  resources :blocks

  resources :cols

  resources :rows

  resources :site_resources

  devise_for :users
  resources :sites
  resources :pages
  post 'pages/sort', :as => :sort_pages
  post 'site_resources/sort', :as => :sort_site_resources
  post 'rows/sort', :as => :sort_rows
  post 'blocks/update_all', :as => :update_all_blocks
  post 'blocks/sort', :as => :sort_blocks
  match 'robots.txt' => 'sites#robots'

  match '', to: 'pages#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  match '/edit', to: 'pages#edit', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  match '/edit_layout', to: 'sites#edit_layout', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  match '/update_layout.:id', to: 'sites#update_layout', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :layout
  get '/:id', to: 'pages#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :page
  put '/:id', to: 'pages#update', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :update_page
  delete '/:id', to: 'pages#destroy', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :destroy_page
  match '/:id/edit', to: 'pages#edit', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :edit_page

  get "home/index"
  get "home/plans"
  get "home/features"
  get "home/about"
  get "home/support"
  root :to => 'home#index'

end

app/models/col.rb
class Col < ActiveRecord::Base
  belongs_to :row
  acts_as_list :scope => :row
  has_many :blocks, :order => "position", :dependent => :destroy
  scope :not_parent, :conditions => "id NOT IN (SELECT DISTINCT col_id FROM blocks WHERE col_id IS NOT NULL)"

end

app/controllers/cols_controller.rb
class ColsController < ApplicationController
  # GET /cols
  # GET /cols.json
  def index
    @cols = Col.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cols }
    end
  end

  # GET /cols/1
  # GET /cols/1.json
  def show
    @col = Col.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @col }
    end
  end

  # GET /cols/new
  # GET /cols/new.json
  def new
    @col = Col.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @col }
    end
  end

  # GET /cols/1/edit
  def edit
    @col = Col.find(params[:id])
  end

  # POST /cols
  # POST /cols.json
  def create

    @row = Row.find(params[:col][:row_id])

    if @row.cols.count < 12
      @page = @row.page
      @col = @row.cols.build(params[:col])
      @block = @col.blocks.build

      respond_to do |format|
        if @col.save
          format.html { redirect_to @col, notice: 'Col was successfully created.' }
          format.js   { render 'rows/create.js' }
          format.json { render json: @col, status: :created, location: @col }
        else
          format.html { render action: "new" }
          format.json { render json: @col.errors, status: :unprocessable_entity }
        end
      end
    else
      return false
    end
  end

  # PUT /cols/1
  # PUT /cols/1.json
  def update
    @col = Col.find(params[:id])

    respond_to do |format|
      if @col.update_attributes(params[:col])
        format.html { redirect_to @col, notice: 'Col was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @col.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cols/1
  # DELETE /cols/1.json
  def destroy
    @col = Col.find(params[:id])
    @col.destroy
    @page = @col.row.page

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
      format.json { head :no_content }
    end
  end
end

app/helpers/cols_helper.rb
module ColsHelper
end

app/views/cols/_col.html.erb
<li id="<%= col.id %>" data-delete-url="/cols/<%= col.id %>" class="span<%= 12/row.cols.count %> col" style="position: relative; min-height: 60px; list-style:none;">
	<ul class="blocks" style="overflow: visible;" data-update-url="<%= sort_blocks_path %>">
		<%= render col.blocks, :col => col %>
	</ul>
	<% if params[:action] != "show" %>
		<%= render 'cols/edit_col', :col => col %>
	<% end %>
</li>

app/views/cols/_edit_col.html.erb
<%= form_for(Block.new, :remote => true) do |f| %>
	<%= f.hidden_field :col_id, :value => col.id %>
	<%= f.submit raw("&plus;"), :class => "add-block btn btn-mini btn-col" %>
<% end %>

app/views/cols/_form.html.erb
<%= form_for(@col) do |f| %>
  <% if @col.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@col.errors.count, "error") %> prohibited this col from being saved:</h2>

      <ul>
      <% @col.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :col_width %><br />
    <%= f.number_field :col_width %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cols/destroy.js.erb
$("#rows").html("<%= escape_javascript(render(@page.rows)) %>");
Aloha.jQuery('#content').aloha();

app/views/cols/edit.html.erb
<h1>Editing col</h1>

<%= render 'form' %>

<%= link_to 'Show', @col %> |
<%= link_to 'Back', cols_path %>

app/views/cols/index.html.erb
<h1>Listing cols</h1>

<table>
  <tr>
    <th>Row</th>
    <th>Col width</th>
    <th>Position</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cols.each do |col| %>
  <tr>
    <td><%= col.row %></td>
    <td><%= col.col_width %></td>
    <td><%= col.position %></td>
    <td><%= link_to 'Show', col %></td>
    <td><%= link_to 'Edit', edit_col_path(col) %></td>
    <td><%= link_to 'Destroy', col, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Col', new_col_path %>

app/views/cols/new.html.erb
<h1>New col</h1>

<%= render 'form' %>

<%= link_to 'Back', cols_path %>

app/views/cols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Row:</b>
  <%= @col.row %>
</p>

<p>
  <b>Col width:</b>
  <%= @col.col_width %>
</p>

<p>
  <b>Position:</b>
  <%= @col.position %>
</p>


<%= link_to 'Edit', edit_col_path(@col) %> |
<%= link_to 'Back', cols_path %>