config/routes.rb
Cms::Application.routes.draw do
  resources :blocks

  resources :cols

  resources :rows

  resources :site_resources

  devise_for :users
  resources :sites
  resources :pages
  post 'pages/sort', :as => :sort_pages
  post 'site_resources/sort', :as => :sort_site_resources
  post 'rows/sort', :as => :sort_rows
  post 'blocks/update_all', :as => :update_all_blocks
  post 'blocks/sort', :as => :sort_blocks
  match 'robots.txt' => 'sites#robots'

  match '', to: 'pages#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  match '/edit', to: 'pages#edit', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  match '/edit_layout', to: 'sites#edit_layout', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  match '/update_layout.:id', to: 'sites#update_layout', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :layout
  get '/:id', to: 'pages#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :page
  put '/:id', to: 'pages#update', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :update_page
  delete '/:id', to: 'pages#destroy', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :destroy_page
  match '/:id/edit', to: 'pages#edit', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :edit_page

  get "home/index"
  get "home/plans"
  get "home/features"
  get "home/about"
  get "home/support"
  root :to => 'home#index'

end

app/models/block.rb
class Block < ActiveRecord::Base
  before_destroy :get_parent
  after_destroy :destroy_orphaned_parent

  belongs_to :col
  acts_as_list :scope => :col

  private
    def get_parent
      @parent_id = self.col_id
    end
    def destroy_orphaned_parent
      @col = Col.find(@parent_id)
      @row = @col.row
      if @col.blocks.count == 0
        @col.destroy
      end
      if @row.cols.count == 0
        @row.destroy
      end
    end

end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  # GET /blocks
  # GET /blocks.json
  def index
    @blocks = Block.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blocks }
    end
  end

  # GET /blocks/1
  # GET /blocks/1.json
  def show
    @block = Block.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @block }
    end
  end

  # GET /blocks/new
  # GET /blocks/new.json
  def new
    @block = Block.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @block }
    end
  end

  # GET /blocks/1/edit
  def edit
    @block = Block.find(params[:id])
  end

  # POST /blocks
  # POST /blocks.json
  def create
    if params[:col_id]
      params[:block][:col_id] = params[:col_id]
    end

    @col = Col.find(params[:block][:col_id])
    @page = @col.row.page

    params[:block][:content] = "click to start typing..."
    @block = Block.new(params[:block])

    respond_to do |format|
      if @block.save
        format.html { redirect_to @block, notice: 'Block was successfully created.' }
        format.js   { render 'rows/create.js' }
        format.json { render json: @block, status: :created, location: @block }
      else
        format.html { render action: "new" }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blocks/1
  # PUT /blocks/1.json
  def update
    @block = Block.find(params[:id])
    @page = @block.col.row.page

    respond_to do |format|
      if @block.update_attributes(params[:block])
        format.html { redirect_to @block, notice: 'Block was successfully updated.' }
        format.js   { render 'rows/create.js' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_all
    params.each do |id, content|
      Block.update_all({content: content}, {id: id})
    end
    render nothing: true
  end

  # DELETE /blocks/1
  # DELETE /blocks/1.json
  def destroy
    @block = Block.find(params[:id])
    @page = @block.col.row.page
    @block.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def sort
    if !params[:block].nil?
      params[:block].each_with_index do |id, index|
        Block.update_all({position: index+1, col_id: params[:col]}, {id: id})
      end
    end

    @col = Col.find(params[:col][0])
    @page = @col.row.page

    Col.not_parent.each do |col|
      col.destroy
    end
    Row.not_parent.each do |row|
      row.destroy
    end

    respond_to do |format|
      format.js   { render 'rows/create.js' }
    end

  end
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/views/blocks/_block.html.erb
<% if params[:action] != "show" %>
<li class="block-container" id="block_<%= block.id %>" data-delete-url="<%= block_url(block) %>" style="list-style: none; position: relative">
	<span class="btn btn-mini handle"><i class="icon-move"></i></span>
	<div class='block' id="<%= block.id %>" data-id="<%= block.id %>" data-update-url="<%= update_all_blocks_url %>">
		<%= raw block.content %>
	</div>
</li>
<% else %>
<div class="block">
	<%= raw block.content %>
</div>
<% end %>

app/views/blocks/_form.html.erb
<%= form_for(@block) do |f| %>
  <% if @block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
      <% @block.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blocks/edit.html.erb
<h1>Editing block</h1>

<%= render 'form' %>

<%= link_to 'Show', @block %> |
<%= link_to 'Back', blocks_path %>

app/views/blocks/index.html.erb
<h1>Listing blocks</h1>

<table>
  <tr>
    <th>Col</th>
    <th>Content</th>
    <th>Position</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blocks.each do |block| %>
  <tr>
    <td><%= block.col %></td>
    <td><%= block.content %></td>
    <td><%= block.position %></td>
    <td><%= link_to 'Show', block %></td>
    <td><%= link_to 'Edit', edit_block_path(block) %></td>
    <td><%= link_to 'Destroy', block, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Block', new_block_path %>

app/views/blocks/new.html.erb
<h1>New block</h1>

<%= render 'form' %>

<%= link_to 'Back', blocks_path %>

app/views/blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Col:</b>
  <%= @block.col %>
</p>

<p>
  <b>Content:</b>
  <%= @block.content %>
</p>

<p>
  <b>Position:</b>
  <%= @block.position %>
</p>


<%= link_to 'Edit', edit_block_path(@block) %> |
<%= link_to 'Back', blocks_path %>