config/routes.rb
Cms::Application.routes.draw do
  resources :blocks

  resources :cols

  resources :rows

  resources :site_resources

  devise_for :users
  resources :sites
  resources :pages
  post 'pages/sort', :as => :sort_pages
  post 'site_resources/sort', :as => :sort_site_resources
  post 'rows/sort', :as => :sort_rows
  post 'blocks/update_all', :as => :update_all_blocks
  post 'blocks/sort', :as => :sort_blocks
  match 'robots.txt' => 'sites#robots'

  match '', to: 'pages#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  match '/edit', to: 'pages#edit', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  match '/edit_layout', to: 'sites#edit_layout', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  match '/update_layout.:id', to: 'sites#update_layout', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :layout
  get '/:id', to: 'pages#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :page
  put '/:id', to: 'pages#update', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :update_page
  delete '/:id', to: 'pages#destroy', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :destroy_page
  match '/:id/edit', to: 'pages#edit', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :edit_page

  get "home/index"
  get "home/plans"
  get "home/features"
  get "home/about"
  get "home/support"
  root :to => 'home#index'

end

app/views/pages/_edit_buttons.html.erb
<% if current_user && current_user.id == @site.user_id %>
	<div class="edit-buttons">
		<% if @page %>
			<%= link_to 'Edit', edit_page_path(@page) %>
		<% else %>
			<%= link_to 'Edit', edit_url %>
		<% end %>
	</div>
<% end %>

app/views/pages/_form.html.erb
<%= form_for(@page, :remote => true, :html => {:class => 'ctrl'}) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :title, :class => "title" %>
  </div>
  <div class="field">
    <%= f.hidden_field :position %>
  </div>


  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, :style => "width: 100%" %>
  </div>
  <div class="field">
    <%= f.collection_select(:parent, @pages, :id, :title, :include_blank => true)%>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/pages/_meta_form.html.erb
<%= form_for(@page, :remote => true, :html => {:class => 'ctrl'}) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :seo_title, "SEO Title" %>
    <%= f.text_field :seo_title %>
  </div>
  <div class="row-fluid">
	  <div class="span6">
	    <%= f.label :seo_meta, "Meta Description" %>
	    <%= f.text_area :seo_meta, :rows => '5', :style => "width: 100%" %>
	  </div>
	  <div class="span6">
	    <%= f.label :seo_keywords, "Meta Keywords" %>
	    <%= f.text_area :seo_keywords, :rows => '5', :style => "width: 100%" %>
	  </div>
  </div>

<% end %>

app/views/pages/_new_form.html.erb
<div id="add_page" class="modal modal-fixed" style="display: none;">
	<%= form_for( @new_page, :style => "margin: 0px;" ) do |f| %>
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Add a Page</h3>
  </div>
  <div class="modal-body">
		  <% if @new_page.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@new_page.errors.count, "error") %> prohibited this page from being saved:</h2>

		      <ul>
		      <% @new_page.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>

		  <div class="field">
		    <%= f.label :title %>
		    <%= f.text_field :title %>
		  </div>
		  <!-- <div class="field">
		    <%= f.label :parent %>
		    <%= f.collection_select(:parent, @pages, :id, :title, :include_blank => true)%>
		  </div> -->

  </div>
  <div class="modal-footer">
  		<a href="#" class="btn btn-inverse" data-dismiss="modal">Cancel</a>
  		<%= f.submit :class => "btn" %>
      <div class="clear"></div>
  </div>
  <% end %>
</div>

app/views/pages/edit.html.erb
<ul id="rows" data-update-url="<%= sort_rows_url %>" style="margin: 0px;">
	<%= render @page.rows %>
</ul>

<%= form_for(@row, :remote => true) do |f| %>
  <% if @row.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@row.errors.count, "error") %> prohibited this row from being saved:</h2>

      <ul>
      <% @row.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%= f.hidden_field :page_id %>
  <%= f.hidden_field :position %>

  <div class="actions">
    <%= f.submit "+ Row", :class => "btn btn-mini", :id => "add-row" %>
  </div>
<% end %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table class="table">
	<thead>
  <tr>
    <th>Title</th>
    <th>Slug</th>
    <th>Order</th>
    <th>Parent</th>
    <th>Content</th>
    <th>Seo title</th>
    <th>Seo meta</th>
    <th>Seo keywords</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
	</thead>
	<tbody>
<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= page.slug %></td>
    <td><%= page.position %></td>
    <td><%= page.parent %></td>
    <td><%= page.content %></td>
    <td><%= page.seo_title %></td>
    <td><%= page.seo_meta %></td>
    <td><%= page.seo_keywords %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
	</tbody>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'new_form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<%= render @page.rows %>

<%= render 'pages/edit_buttons' %>