config/routes.rb
Cms::Application.routes.draw do
  resources :blocks

  resources :cols

  resources :rows

  resources :site_resources

  devise_for :users
  resources :sites
  resources :pages
  post 'pages/sort', :as => :sort_pages
  post 'site_resources/sort', :as => :sort_site_resources
  post 'rows/sort', :as => :sort_rows
  post 'blocks/update_all', :as => :update_all_blocks
  post 'blocks/sort', :as => :sort_blocks
  match 'robots.txt' => 'sites#robots'

  match '', to: 'pages#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  match '/edit', to: 'pages#edit', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  match '/edit_layout', to: 'sites#edit_layout', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  match '/update_layout.:id', to: 'sites#update_layout', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :layout
  get '/:id', to: 'pages#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :page
  put '/:id', to: 'pages#update', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :update_page
  delete '/:id', to: 'pages#destroy', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :destroy_page
  match '/:id/edit', to: 'pages#edit', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, :as => :edit_page

  get "home/index"
  get "home/plans"
  get "home/features"
  get "home/about"
  get "home/support"
  root :to => 'home#index'

end

app/models/layout.rb
class Layout < ActiveRecord::Base
  has_many :sites
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Condo Motion</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <style type="text/css">
  	ul.home_nav {
			float: right;
			margin-top: 20px;
			font-size: 15px;
			color: #fff;
			font-weight: normal;
  	}
  	ul.home_nav li a {
			color: #fff;
			text-decoration: none;
			text-shadow: 0 2px 3px rgba(0, 0, 0, 0.35);
  	}
  	ul.home_nav li {
			display: inline-block;
			margin-left: 15px;
  	}
  	h1 {
  		font-size: 30px;
  		margin-bottom: 15px;
  		line-height: 1.2;
  		font-family: 'Candal', sans-serif;
  		letter-spacing: -1px;
  		text-shadow: 0 2px 3px rgba(0, 0, 0, 0.35);
  		color: rgba(255, 255, 255, 0.9);
  	}
  	.subtext {
  		font-size: 22px;
  		margin-bottom: 20px;
  		font-weight: 200;
  		line-height: 1.5;
  		text-shadow: 0 2px 3px rgba(0, 0, 0, 0.35);
  		color: rgba(255, 255, 255, 0.9);
  	}
  	body {
  		background-color: #336895;
  		color: white;
  		background-image: -webkit-gradient(linear, left center, right center, from(#336895), to(#336895));
  		background-image: -webkit-linear-gradient(left, #336895 0%,#618CB7 50%,#336895 100%);
  		background-image: -moz-linear-gradient(left,#336895 0%,#618CB7 50%, #336895 100%);
  		background-image: -ms-linear-gradient(left, #336895 0%, #618CB7 50%, #336895 100%);
  		background-image: -o-linear-gradient(left, #336895 0%, #618CB7 50%, #336895 100%);
  		background-image: linear-gradient(left, #336895 0%, #618CB7 50%, #336895 100%);
  	}
  	.page-content {
  		margin-top: 20px;
  		background: #EDEDED;
  		color: #333;
  		border-top: 1px solid white;
  		border-left: 1px solid white;
  		border-right: 2px solid #DDDFE1;
  		border-bottom: 2px solid #DDDFE1;
  		-moz-box-shadow: 1px 1px 3px #333;
  		-webkit-box-shadow: 1px 1px 3px #333;
  		-box-shadow: 1px 1px 3px #333;
  		-moz-border-radius: 3px;
  		-webkit-border-radius: 3px;
  		border-radius: 3px;
  		margin-bottom: 30px;
  	}
  	.footer-links {
  		font-size: 16px;
  		color: #F1F1F1;
  		text-align: center;
  	}
  	.footer-links a {
			padding-left: 15px;
			color: #F1F1F1;
			text-decoration: none;
			font-weight: normal;
		}
		.trial {
			font-size: 20px;
			color: #999;
			/*text-shadow: 1px 1px 3px #fff;*/
			text-shadow: white 1px 1px 0;
		}
		.pricing-title {
			background: #3E4859;
			color: #FFF;
			font-size: 20px;
			padding: 10px 0px;
			font-weight: normal;
			position: relative;
		}
		.pricing-price {
			font-size: 60px;
			line-height: 1;
			padding: 20px 0px;
			background: #233143;
			color: #fff;
			text-shadow: #777 -1px -1px 0;
		}
		.pricing-price small {
			font-size: 20px;
		}
		.pricing-included {
			background: whiteSmoke;
			padding: 20px;

		}
  </style>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="favicon.png">
</head>
<body>

<div id="wrap">
	<div id="main" class="container" style="padding-top: 30px;">
		<% if flash[:alert] %>
		  <p class="alert alert-error"><a class="close" data-dismiss="alert">×</a> <%= flash[:alert] %></p>
		<% end %>
		<% if flash[:notice] %>
		  <p class="alert alert-success"><a class="close" data-dismiss="alert">×</a> <%= flash[:notice] %></p>
		<% end %>

		<%= link_to image_tag("logo_light.png"), home_index_path, :style => "float: left;" %>
		<ul class="home_nav">
			<li><%= link_to 'Plans & Pricing', home_plans_path %></li>
			<li><%= link_to 'Features', home_features_path %></li>
			<li><%= link_to 'About', home_about_path %></li>
			<li><%= link_to 'Support', home_support_path %></li>
			<% if user_signed_in? %>
				<li><%= link_to "Sign Out", destroy_user_session_url(subdomain: false), :method => :delete, :class => "btn btn-large", :style => "color: #333;" %></li>
				<li><%= link_to "Dashboard", sites_path, :class => "btn btn-large", :style => "color: #333;" %></li>
			<% else %>
				<li><%= link_to "Log In", new_user_session_path, :class => "btn btn-large", :style => "color: #333;" %></li>
				<li><%= link_to "Sign Up", "#myModal", :class => "btn btn-large btn-success", 'data-toggle' => "modal" %></li>
			<% end %>
		</ul>

		<div class="clear"></div>

		<%= yield %>

		<div class="modal hide fade" id="myModal">
		  <div class="modal-header">
		    <a class="close" data-dismiss="modal">×</a>
		    <h3>Sign up</h3>
		  </div>
		  <%= form_for("user", :url => user_registration_path, :style => "margin: 0px;") do |f| %>
		  <div class="modal-body">
			  <div><%= f.email_field :email, :class => "large", :placeholder => "Email" %></div>
			  <div><%= f.password_field :password, :class => "large", :placeholder => "Password" %></div>
			  <div><%= f.password_field :password_confirmation, :class => "large", :placeholder => "Confirm Password" %></div>
			</div>
		  <div class="modal-footer">
		    <a href="#" class="btn" data-dismiss="modal">Close</a>
		    <%= f.submit "Sign up", :class => "btn btn-primary" %>
		  </div>
		  <% end %>
		</div>

	</div> <!-- /container -->
</div> <!-- /wrap -->

<%= render 'devise/footer'%>

</body>
</html>

app/views/layouts/codemirror.html.erb
<!doctype html>
<html>
  <head>
    <title>Condo Motion</title>
    <meta charset=utf-8>
    <script src=/codemirror/lib/codemirror.js></script>
    <script src=/codemirror/mode/xml/xml.js></script>
    <script src=/codemirror/mode/javascript/javascript.js></script>
    <script src=/codemirror/mode/css/css.js></script>
    <script src=/codemirror/mode/htmlmixed/htmlmixed.js></script>
    <link rel=stylesheet href=/codemirror/lib/codemirror.css>
    <link rel="stylesheet" href="/codemirror/theme/night.css">
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
    <!-- <link rel=stylesheet href=../doc/docs.css> -->

    <!-- jScrollPane -->

		<link type="text/css" href="/codemirror/jscrollpane/style/jquery.jscrollpane.css" rel="stylesheet" media="all" />
		<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js
" %>
		<%= javascript_include_tag "ctrl" %>
    <%= javascript_include_tag "sites" %>
		<script type="text/javascript" src="/codemirror/jscrollpane/script/jquery.mousewheel.js"></script>
		<script type="text/javascript" src="/codemirror/jscrollpane/script/mwheelIntent.js"></script>
		<script type="text/javascript" src="/codemirror/jscrollpane/script/jquery.jscrollpane.min.js"></script>

	  <%= csrf_meta_tags %>

    <style type=text/css>
    	html, body {
    		width: 100%;
    		height: 100%;
    		padding: 0px;
    		margin: 0px;
    	}
      .CodeMirror {
        float: left;
        width: 45%;
        position: absolute;
        top: 50px;
        bottom: 0px;
      }
      iframe {
        width:55%;
        height: 100%;
        float: left;
        border: 0px;
        margin-left: 45%;
      }
      .CodeMirror-scroll {
			  overflow-y: auto;
			  overflow-x: hidden;
			  height: 100%;
			  /* This is needed to prevent an IE[67] bug where the scrolled content
			     is visible outside of the scrolling box. */
			  position: relative;
			}
			.activeline {
				background: #4e545b !important;
			}
			.CodeMirror code, .CodeMirror pre {
      	color: #f1f1f1;
      }
      .CodeMirror-gutter-text pre {
      	color: #666;
      }
      #buttons {
      	width: 45%;
      	position: absolute;
      	top: 0px;
      	height: 50px;
      	color: #333;
      	left: 0px;
      	background-color: #4E545B;
      }
      #buttons-color {
      	height: 30px;
      	padding: 10px 20px;
      	background: rgba(0,0,0,0.35);
      }
    </style>
  </head>
  <body>

  <div id="buttons">
  	<div id="buttons-color" style="">
			<%= link_to "Cancel", edit_url, :class => "btn btn-inverse" %>
			<%= link_to "Save", "#", :class => "btn btn-success", :id => "save", :style => 'margin-left: 10px;' %>
		</div>
  </div>

	<%= render 'layout_form' %>

    <iframe id='preview' src="<%= page_url(@page) %>"></iframe>

    <script type="text/javascript">
      var delay;

     	var editor = CodeMirror.fromTextArea(document.getElementById('layout_content'), {
        mode: 'text/html',
        tabMode: 'indent',
        theme: 'night',
        lineNumbers: true,
        lineWrapping: true,
        onChange: function() {
          //clearTimeout(delay);
          //delay = setTimeout(updatePreview, 100);
        },
        onCursorActivity: function() {
			    editor.setLineClass(hlLine, null);
			    hlLine = editor.setLineClass(editor.getCursor().line, "activeline");
			  }
      });

	    var hlLine = editor.setLineClass(0, "activeline");


      function updatePreview() {
        var previewFrame = document.getElementById('preview');
        var preview =  previewFrame.contentDocument ||  previewFrame.contentWindow.document;
        preview.open();
        preview.write("<style type=text/css>body {overflow-x: hidden;}</style>" + editor.getValue());
        preview.close();
        // $('#preview').attr('src', $('#preview').attr('src'));
      }
      //setTimeout(updatePreview, 100);

			// $('.CodeMirror-scroll').jScrollPane({
			 // autoReinitialise: true,
			 // mouseWheelSpeed: 100
			// });

			$("#save").click(function(){
				$(".ctrl").submit();
				return false;
			});


    </script>
  </body>
</html>

app/views/layouts/custom.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- <title><%= @site.seo_title %><% if !@page.nil? && @page.seo_title != "" %> | <%= @page.seo_title %><% end %></title> -->
<title><%= seo_title(@page) %></title>
<meta content="<%= meta_description(@page) %>" name="description">
<meta content="<%= meta_keywords(@page) %>" name="keywords">
<style>
body {
  padding-top: 60px;
}
.edit-buttons {
	position: fixed;
	bottom: 15px;
	right: 15px;
	background: #000;
	color: #fff;
	border-radius: 20px;
	-webkit-border-radius: 20px;
	-moz-border-radius: 20px;
}
.edit-buttons a {
	text-decoration: none;
	color: #FFF;
	padding: 10px 20px;
	display: block;
	border-radius: 20px;
}
ul.blocks {
	margin: 0px;
}
</style>

<% @site.site_resources.css.each do |stylesheet| %>
  	<link href="<%= (stylesheet.resource_url == '') ? stylesheet.resource.url : stylesheet.resource_url %>" rel="stylesheet" type="text/css">
<% end %>

<link rel="shortcut icon" href="<%= @site.favicon.url(:icon) %>">
</head>

<%= liquidize @current_site.layout.content, {
	'page_content' => yield,
	'site' => @site,
	'page' => @page,
	'user' => @user
	}
%>

<% @site.site_resources.js.each do |js| %>
		<script src="<%= (js.resource_url == '') ? js.resource.url : js.resource_url %>" type="text/javascript"></script>
<% end %>

</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Condo Motion</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/favicon.png">
</head>


  <body>

	<div id="side-nav-primary">
		<div style="padding-top: 30px; text-align: center;">
<!-- 		icons are adjusted to 55% lightness and then 95% again for the white ones	 -->
			<ul class="nav nav-list nav-list-padded" style="padding: 0px;">
				<li class="icon-pages-lg active-lg link"><a rel="tooltip" data-original-title="Pages & Content" href="#pages"></a></li>
				<li class="icon-group-lg link"><a rel="tooltip" data-original-title="Users" href="#users"></a></li>
				<li class="icon-cardio-lg link"><a rel="tooltip" data-original-title="Activity & Comments" href="#activity"></a></li>
				<li class="icon-usd-lg link"><a rel="tooltip" data-original-title="Payments" href="#payments"></a></li>
				<li class="icon-cogs-lg link"><a rel="tooltip" data-original-title="Settings" href="#settings"></a></li>

				<li class="icon-imac-lg link"><%= link_to "", '#sites', 'data-original-title' => "Your Sites", :rel => "tooltip"%></li>
				<li class="icon-power-lg"><%= link_to "", destroy_user_session_url(subdomain: false), method: :delete, 'data-original-title' => "Sign Out", :rel => "tooltip" %></li>
				<!-- <li class="icon-eye-lg"><a rel="tooltip" data-original-title="Preview" id="preview" href="#"></a></li> -->
			</li>
    </div>
	</div>
	<div id="#pages" class="side-nav-secondary">
		<div style="padding-top: 30px;">
			<h4 class="site-title-preview"><%= @site.title %></h4>
			<!-- <h4>Pages</h4> -->
			<ul class="nav nav-list sortable" data-update-url="<%= sort_pages_url %>">
	  <!--     <li class="<%= @page.nil? ? 'active site-title' : 'site-title' %> ui-state-disabled"><%= link_to '<i class="icon-home"></i> '.html_safe+@site.title, edit_url, :class => 'site-title' %></li> -->

	      <% @pages.each do |page| %>
				  <%= content_tag_for :li, page, :class => ((!@page.nil? && @page.id == page.id) ? 'active page-title' : ''), :style => "position: relative;"  do %>
				  	<%= link_to ('<i class="' + ((page.position == 1) ? 'icon-home' : 'icon-file') + ' move"></i> ').html_safe+page.title, edit_page_path(page), :class => 'page-title' %>
				  	<%= link_to('×', destroy_page_path(page), :method => 'delete', :confirm => "Are you sure?", :class => "close delete" ) %>
				  <% end %>
				<% end %>

				<li class="ui-state-disabled"><a href="#add_page" data-toggle="modal" data-backdrop="true" data-keyboard="true" style="color: #333;"><i class="icon-plus"></i> Add a Page</a></li>
	    </ul>

	    <hr/>

	    <!-- <h4>Other</h4> -->
	    <ul class="nav nav-list">
	      <!-- <li><a href="#"><i class="icon-folder-open"></i> Files</a></li> -->
	      <li><%= link_to raw("<i class='icon-edit'></i> Edit Layout"), edit_layout_url %></li>
	    </ul>
    </div>
	</div>

	<div id="#sites" class="side-nav-secondary" style="display: none;">
		<div style="padding-top: 30px;">
			<h4>Your Sites</h4>
			<ul class="nav nav-list"">
	      <% @sites.each do |site| %>
				  <%= content_tag_for :li, site, :class => ((@site.id == site.id) ? 'active site-title' : 'site-title'), :style => "position: relative;"  do %>
				  	<%= link_to '<i class="icon-home"></i> '.html_safe+site.title, edit_url(subdomain: site.subdomain), :class => ((@site.id == site.id) ? 'site-title' : '') %>
				  	<%= link_to('×', site, :method => 'delete', :confirm => "Are you sure?", :class => "close delete" ) %>
				  <% end %>
				<% end %>
				<li class="ui-state-disabled"><a href="#add_site" data-toggle="modal" data-backdrop="true" data-keyboard="true" style="color: #333;"><i class="icon-plus"></i> Add a Site</a></li>
	    </ul>
    </div>
	</div>
	<div id="#settings" class="side-nav-secondary" style="display: none;">
		<div style="padding-top: 30px;">
			<h4><%= @site.title %></h4>
			<ul class="nav nav-list">
	      <li style="position: relative;">
	      	<%= link_to '<i class="icon-wrench"></i> General'.html_safe, edit_site_url(@site)+"#settings" %>
			  <!-- 	<a href="#"><i class="icon-wrench"></i> General</a> -->				 </li>
	    </ul>
    </div>
	</div>

	<div id="canvas">
		<div id="canvas-padding">
				<%= form_for((!@page.nil? ? @page : @site), :html => {:class => 'ctrl', :remote => true }) do |f| %>
				  <div class="field">
				    <%= f.hidden_field :title, :class => 'title' %>
				  </div>
				<% end %>
			<input type="text" value="<%= !@page.nil? ? @page.title : @site.title %>" id="<%= !@page.nil? ? 'page' : 'site' %>-title"/><div style="position: relative; display: none; top: 8px;" id="saving-indicator">Saving...</div>
			<i class="icon-cogs-lg pull-right" id="page-settings-toggle" style="width: 26px; height: 26px; margin-bottom: 5px; margin-left: 7px; cursor: pointer;"></i>
			<%= link_to raw('<i class="icon-eye-lg pull-right" id="page-design-toggle" style="width: 31px; height: 26px; margin-bottom: 5px; margin-left: 7px; cursor: pointer;"></i>'), ( !@page.nil? ? page_url(@page) : root_url(subdomain: @site.subdomain) ) %>

			<i class="icon-lock-lg pull-right" id="page-permissions-toggle" style="width: 26px; height: 26px; margin-bottom: 5px; margin-left: 7px; cursor: pointer;"></i>
			<div class="clear"></div>
			<div id="page-settings" class="row-fluid" style="border-top: 1px solid #f1f1f1; border-bottom: 1px solid #f1f1f1; display: none;">
				<div class="tabbable tabs-left row-fluid">
				  <ul class="nav nav-tabs span3" style="margin: 0px;">
	          <li class="active"><a href="#lA" data-toggle="tab" style='border-top: none;'><i class="icon-book"></i> CSS &amp; JS</a></li>
	          <li class=""><a href="#lB" data-toggle="tab"><i class="icon-pencil"></i> Meta </a></li>
	          <li class=""><a href="#lC" data-toggle="tab"><i class="icon-search"></i> Search & Tracking</a></li>
	        </ul>
				  <div class="tab-content span9" style="margin: 0px;">
	          <div class="tab-pane active" id="lA">
	            <%= render 'site_resources/site_resources' %>
	          </div>
	          <div class="tab-pane" id="lB">
	          	<% if @page %>
	            	<%= render 'pages/meta_form' %>
	            <% else %>
	            	<%= render 'sites/meta_form' %>
	            <% end %>
	          </div>
	          <div class="tab-pane" id="lC">
	            	<%= render 'sites/robots_form' %>
	          </div>
	        </div>
				</div>
			</div>
			<div class="row-fluid" style="position: relative; margin-top: 10px;">
		  	<%= yield %>
		  </div>


		</div>
	</div>

  <%= render "pages/new_form" %>
  <%= render "sites/new_form" %>


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

</head>

		<script type="text/javascript">

			$(function(){
				$("#page-settings-toggle").click(function(){
					$("#page-settings").slideToggle('fast');
				});

				// $('.link').click(function(){
					// var panel = $(this).attr('id');
					// $(this).siblings('li').removeClass('active-lg');
					// $(this).addClass('active-lg');
					// $(".side-nav-secondary").hide()
					// $(".side-nav-secondary#"+panel).show()
					// return false;
				// });

				$("#preview").click(function(){
					$("#side-nav-secondary").toggle();
					if ($("#side-nav-secondary").is(":visible")) {
						$("#canvas-padding").css('padding-left', '350px');
					} else {
						$("#canvas-padding").css('padding-left', '100px');
					}

				});
			});
		</script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Condo Motion</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="favicon.png">
</head>
<body>

<div id="wrap">
	<div id="main" class="container" style="padding-top: <%= yield :padding %>;">
		<% if flash[:alert] %>
		  <p class="alert alert-error"><a class="close" data-dismiss="alert">×</a> <%= flash[:alert] %></p>
		<% end %>
		<% if flash[:notice] %>
		  <p class="alert alert-success"><a class="close" data-dismiss="alert">×</a> <%= flash[:notice] %></p>
		<% end %>

		<%= yield %>

	</div> <!-- /container -->
</div> <!-- /wrap -->

<%= render 'devise/footer'%>

</body>
</html>